module: hook init into cli/run and cli/project
We still face the following error:
File
"/home/simbuerg/.virtualenvs/benchbuild/lib/python3.7/site-packages/dill/_dill.py",
line 474, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'benchbuild.module.bzip2';
'benchbuild.module' is not a package

This is caused by an incompatible module loaded through importlib.